### ISSUE TITLE
Strange sound artifacts in Carnivore MSX cartridge

### ISSUE THREAD

**Issue by svofski** [digital-sound-antiques/vm2413#1]
Hi!

Your vm2413 model comprises a part of https://github.com/RBSC/Carnivore2 cartridge. 

It produces some unwanted sound artefacts. They sound like high pitched buzz and the envelope of the buzz seems to have the same periodicity as the main waveform. Here are some signals that I have recorded:

![Sine](http://i.imgur.com/fDHt5vm.png)  Sounds like: https://instaud.io/19KV

![Mane](http://i.imgur.com/kEFZjYX.png) Sounds like: https://instaud.io/19KX

I used Moonblaster 1.4 MSX tracker to set up the generators because I don't know a better way to test it. I think it's something in the model, because the amplitude of the envelope of the parasitic sound tends to have the same period as the main waveform. 

Do you have any insight on what could be the problem here? Have you ever experienced anything similar? Thank you!

**Comment by okaxaki** [comment]
Hi, 

This kind of problem depends on any stage: compile, synthesis and D/A conversion. 
To isolate the place of the problem occurrence, please make sure MO and RO pin output with the model simulator.
 
If the problem occurs on hardware-level, D/A converter is very suspicious.
What kind of DAC is used with Carnivore?
The VM2413's MO/RO pin output is not a single audio stream. It's time division multiplexed. So it is possible that the pin output contains higher frequency signals which the DAC does not accept.  
The detail of MO/RO output can be found in YM2413 specification.

**Comment by svofski** [comment]
Hi, thanks for the answer!

The DAC used in Carnivore 2 is YAC516-E.

**Comment by okaxaki** [comment]
Hi, 
The DAC seems to accept from 10KHz to 50KHz sampling rate as sigma-delta stream. So the rate conversion is needed. Does your rate converter cares VM2413's multiplexed 3.58MHz stream? I attach the YM2413 MO/RO multiplexed stream spec as follows. 
![2413](https://user-images.githubusercontent.com/8530297/29080652-51f92d0e-7c9b-11e7-8255-c14c10b2e57b.png)

**Comment by svofski** [comment]
Thank you very much for this insight. I have to pass this to the authors of the cartridge. I'm not intimately familiar with their code but from a quick glance over it, it seems that the data stream is passed directly to the DAC.

**Comment by okaxaki** [comment]
Thank you. I misunderstood you as an author of the firmware. Sorry for much technical details!!
I hope this information is useful for the author to investigate the problem.

**Comment by svofski** [comment]
Your technical details are precisely what I was hoping for. I'm very much into technical details of this kind, it's just in this particular case I'm not yet familiar with the specific project. I'm just trying to help solve a problem. Thanks again!
